# Generated by Django 3.2 on 2022-12-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
        migrations.AddField(
            model_name='shop',
            name='image1',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image3',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
