# Generated by Django 3.2 on 2022-12-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221224_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image1',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='image2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='image3',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
