# Generated by Django 3.2 on 2022-12-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221224_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='geo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
    ]
